### ISSUE TITLE
duplicity/_librsyncmodule.c:27:10: fatal error: librsync.h: No such file or directory

### ISSUE THREAD

**Issue by binarykitchen** [henrysher/duplicity#12]
When trying to compile with following command I get the above error

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/michael-heuberger/pip-build-h2FT4j/duplicity/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/michael-heuberger/pip-b8A0xa-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/michael-heuberger/pip-build-h2FT4j/duplicity/
```

Any ideas why?

Here a longer error stack trace

```
    building 'duplicity._librsync' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/duplicity
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c duplicity/_librsyncmodule.c -o build/temp.linux-x86_64-2.7/duplicity/_librsyncmodule.o
    duplicity/_librsyncmodule.c:27:10: fatal error: librsync.h: No such file or directory
     #include <librsync.h>
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I'm on Ubuntu 17.10 btw - thanks for any hints

**Comment by mbgearhead** [comment]
Hi bk, I just ran into this and was able to successfully upgrade from duplicity 0.7.6 to 0.7.14 using pip on Ubuntu 16.04 after having received the identical error. 

There are two problems: 
1. You installation (most likely) doesn't have the librsync header files installed.
    - Install using: "sudo apt update; sudo apt install librsync-dev".

2. Even if the header files were installed, the LD_LIBRARY_PATH environment variable is not configured by default to have these header files in your PATH. 
    - Create the necessary config file (skip this step if the correct file exists):
        "sudo touch /etc/ld.so.conf.d/librsync.so.2.conf"
    - Add the following path to the file in a single line
        "/usr/local/lib"
        Example: "sudo <insert favorite text editor here> /etc/ld.so.conf.d/librsync.so.2.conf"
   - Reinitialize linux's ldconfig cache:
        "sudo ldconfig"

Hope this helps!

**Comment by binarykitchen** [comment]
ah, that worked - thanks man

and shouldn't this be documented?

**Comment by mbgearhead** [comment]
Honestly, this dependency on that particular header file should not break the upgrade from earlier versions of the duplicity package... Glad to hear this helped!

**Comment by mirekphd** [comment]
Installing librsync-dev helped me too with failing pip install of duplicity on one remote 17.10 Ubuntu machine. 

The error message was the same as above:
`duplicity/_librsyncmodule.c:27:10: fatal error: librsync.h: No such file or directory`
and
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

IMO librsync-dev (rsync remote-delta algorithm library (development)) should be added to the Requirements section of your docs.

**Comment by JavaScriptDude** [comment]
Just hit this bug on duplicity 0.8.23 on a modern FreeBSD PKG install. Modern Debian apt package is 0.8.22 LOL. Now trying to get it installed using python pip directly...

**Comment by axi** [comment]
installing ```librsync-dev``` also worked for me on Ubuntu 22.04 jammy
